source :rubygems

gemspec

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
end

group :test do
  gem 'sqlite3'
  gem 'debugger'
  gem 'guard-minitest'
  gem 'guard', '= 1.0.3'

  gem 'capybara'
  gem 'selenium-webdriver', '~> 2.21'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'launchy'

  gem 'mocha', require: false

  # for fake data in testing
  gem 'faker'

  # for capture response from payment gateways like Authorize.net
  gem 'vcr'

  # vcr uses webmock
  gem 'webmock'

  gem 'nimbleshop_simply',           path: '../nimbleshop_simply'

  gem 'nimbleshop_paypalwp',         path: '../nimbleshop_paypalwp'
  gem 'nimbleshop_authorizedotnet',  path: '../nimbleshop_authorizedotnet'
  gem 'nimbleshop_splitable',        path: '../nimbleshop_splitable'
  gem 'nimbleshop_cod',              path: '../nimbleshop_cod'

end
