# encoding: UTF-8
require 'bundler/gem_tasks'
require 'rake/testtask'
require 'rdoc/task'

desc 'Default: run tests'
task :default => [:test]
task :test => ['nimbleshop_core:test_full']

namespace :nimbleshop_core do

  task :test_full do
    p = File.expand_path('../test/myshop', __FILE__)
    abort 'Test app is missing. First execute "rake nimbleshop:setup:test_app"' unless File.directory?(p)
    Rake::Task["nimbleshop_core:test"].invoke
  end

  desc 'Run nimbleshop_core tests.'
  Rake::TestTask.new(:test) do |t|
    t.libs << 'lib'
    t.libs << 'test'
    t.pattern = 'test/**/*_test.rb'
    t.verbose = true
  end

end
