eval(File.read(Pathname.new(File.dirname(__FILE__)).join('..', '..',  'dev', 'common_gemfile.rb').to_s))

gemspec


gem 'nimbleshop_core',             path: './../../nimbleshop_core'
gem 'nimbleshop_simply',           path: './../../themes/nimbleshop_simply'

gem 'nimbleshop_cod',              path: './../../payment_methods/nimbleshop_cod'
gem 'nimbleshop_authorizedotnet',  path: './../../payment_methods/nimbleshop_authorizedotnet'
gem 'nimbleshop_splitable',        path: './../../payment_methods/nimbleshop_splitable'
gem 'nimbleshop_stripe',           path: './../../payment_methods/nimbleshop_stripe'

gem 'activemerchant'
