eval(File.read(Pathname.new(File.dirname(__FILE__)).join('..', 'dev', 'common_gemfile.rb').to_s))

gemspec

gem 'nimbleshop_simply',           path: '../nimbleshop_simply'
gem 'nimbleshop_cod',              path: '../nimbleshop_cod'
gem 'nimbleshop_core',             path: '../nimbleshop_core'
gem 'nimbleshop_authorizedotnet',  path: '../nimbleshop_authorizedotnet'
gem 'nimbleshop_splitable',        path: '../nimbleshop_splitable'

gem 'activemerchant'
