eval(File.read(Pathname.new(File.dirname(__FILE__)).join('..', '..',  'dev', 'common_gemfile.rb').to_s))

gemspec

gem 'nimbleshop_core',             path: './../../nimbleshop_core'
gem 'nimbleshop_simply',           path: './../../themes/nimbleshop_simply'

gem 'nimbleshop_cod',              path: './../../payment_methods/nimbleshop_cod'
gem 'nimbleshop_splitable',        path: './../../payment_methods/nimbleshop_splitable'
gem 'nimbleshop_paypalwp',         path: './../../payment_methods/nimbleshop_paypalwp'
gem 'nimbleshop_stripe',           path: './../../payment_methods/nimbleshop_stripe'

gem 'activemerchant'
