# encoding: UTF-8
require 'bundler/gem_tasks'
require 'rake/testtask'
require 'rdoc/task'

desc 'Default: run tests'
task :default => ['nimbleshop_authorizedotnet:test']
task :test => ['nimbleshop_authorizedotnet:test']

namespace :nimbleshop_authorizedotnet do

  desc 'Run nimbleshop_authorizedotnet tests.'
  Rake::TestTask.new(:test) do |t|
    t.libs << 'lib'
    t.libs << 'test'
    t.pattern = 'test/**/*_test.rb'
    t.verbose = true
  end

end
